server:
  port: 8081

spring:
  application:
    name: auth-service
  config:
    import: "optional:configserver:http://localhost:8888"
  datasource:
    url: jdbc:postgresql://localhost:5432/hospital_auth
    username: hospital
    password: hospital123
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: health,info

auth:
  jwt:
    issuer: hospital-auth-service
    secret: "local-dev-secret-change-me-local-dev-secret-change-me"
    access-token-ttl-minutes: 180
  refresh-token:
    ttl-days: 30
