server:
  port: 8080

spring:
  application:
    name: api-gateway
  config:
    import: "optional:configserver:http://localhost:8888"
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: false
              lower-case-service-id: true
          routes:
            - id: auth-service
              uri: lb://auth-service
              predicates:
                - Path=/api/auth/**

            - id: patient-service
              uri: lb://patient-service
              predicates:
                - Path=/api/patients/**

            - id: appointment-service
              uri: lb://appointment-service
              predicates:
                - Path=/api/appointments/**,/api/departments/**,/api/doctors/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

auth:
  jwt:
    issuer: hospital-auth-service
    secret: "local-dev-secret-change-me-local-dev-secret-change-me"

management:
  endpoint:
    gateway:
      access: read-only
  endpoints:
    web:
      exposure:
        include: health,info,gateway

logging:
  level:
    com.duy.hospital.apigateway: INFO
    org.springframework.cloud.gateway: INFO
